name: Auto Merge and Update Branches

on:
  schedule:
    - cron: '0 0 * * *'  # Executa todos os dias à meia noite
  push:
    branches:
      - dev-branch-1
      - dev-branch-2  # As branches de desenvolvimento que você deseja atualizar.

env:
  USER_NAME: 'GitHub Actions'
  USER_EMAIL: 'github-actions@github.com'
  MAIN_BRANCH: 'main'
  DEV_BRANCHES: 'dev-branch-1 dev-branch-2'  # Lista de branches separadas por espaço

jobs:
  merge_and_update:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Git configuration
        run: |
          git config --global user.name "${{ env.USER_NAME }}"
          git config --global user.email "${{ env.USER_EMAIL }}"

      - name: Merge changes from development branches into main and update them
        run: |
          git fetch origin
          git checkout ${{ env.MAIN_BRANCH }}
          git pull origin ${{ env.MAIN_BRANCH }}

          for branch in ${{ env.DEV_BRANCHES }}; do
            echo "Processing branch $branch..."

            # Merge changes from the development branch into main
            git log --oneline origin/${{ env.MAIN_BRANCH }}..origin/$branch --pretty=oneline > changes.txt || true
            if [ -s changes.txt ]; then
              e
