name: Auto Merge to Main

on:
  schedule:
    - cron: '0 0 * * *'  # Executa todos os dias à meia noite
  push:
    branches:
      - dev-branch-1
      - dev-branch-2  # As branches de desenvolvimento que você deseja mesclar.

env:
  USER_NAME: 'GitHub Actions'
  USER_EMAIL: 'github-actions@github.com'
  MAIN_BRANCH: 'main'
  DEV_BRANCHES: 'dev-branch-1 dev-branch-2'  # Lista de branches separadas por espaço

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Git
        uses: actions/setup-git@v2
        with:
          user-name: ${{ env.USER_NAME }}
          user-email: ${{ env.USER_EMAIL }}

      - name: Merge changes from development branches
        run: |
          git fetch origin
          git checkout ${{ env.MAIN_BRANCH }}
          git pull origin ${{ env.MAIN_BRANCH }}
          for branch in ${{ env.DEV_BRANCHES }}; do
            echo "Checking branch $branch..."
            git log --oneline origin/${{ env.MAIN_BRANCH }}..origin/$branch --pretty=oneline > changes.txt || true
            if [ -s changes.txt ]; then
              echo "Changes detected in $branch, proceeding with merge."
              git merge origin/$branch
              git push origin ${{ env.MAIN_BRANCH }}
            else
              echo "No changes in $branch, skipping merge."
            fi
          done
